name: 'CI'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Cancel previous runs if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-tauri-windows:
    runs-on: windows-latest
    name: 'Test Tauri (Windows)'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend for Tauri
        run: pnpm build

      - name: Check Rust formatting
        run: cargo fmt --manifest-path ./src-tauri/Cargo.toml -- --check

      - name: Run Rust clippy
        run: cargo clippy --manifest-path ./src-tauri/Cargo.toml -- -D warnings

      - name: Run Rust tests
        run: cargo test --manifest-path ./src-tauri/Cargo.toml

      - name: Build Tauri app for Windows
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Don't upload to release, just build
          includeRelease: false
          includeDebug: false

  test-e2e-selenium:
    runs-on: ubuntu-latest
    name: 'E2E Tests (Selenium Web)'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm build

      - name: Start Next.js server
        run: |
          pnpm start &
          sleep 15

      - name: Install Chrome
        uses: nanasess/setup-chromedriver@v2

      - name: Run E2E tests
        run: pnpm test:e2e

  integration-test:
    runs-on: windows-latest
    name: 'Integration Test (Windows)'
    needs: [test-frontend, test-backend, test-tauri-windows, test-e2e-selenium]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Full integration test
        run: |
          # Build frontend
          echo "Building frontend..."
          pnpm build
          
          # Test that Tauri can compile with the built frontend
          echo "Testing Tauri compilation..."
          cd src-tauri
          cargo build --release
          cd ..
          
          # Start Next.js and test API in background
          echo "Testing frontend-backend integration..."
          pnpm start &
          Start-Sleep -Seconds 10
          
          # Test API integration
          try {
            $response = Invoke-WebRequest -Uri "http://localhost:3000/api/cases?caseId=1" -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "✅ API integration test passed"
            } else {
              Write-Host "❌ API integration test failed"
              exit 1
            }
          } catch {
            Write-Host "❌ API integration test failed: $_"
            exit 1
          } finally {
            # Kill the background process
            Stop-Process -Name "node" -Force -ErrorAction SilentlyContinue
          }
          
          echo "✅ Full integration test passed - Tauri + Next.js + API working on Windows" 